/* tslint:disable */
/* eslint-disable */
/**
 * 媒体管理器 API
 * 媒体管理器 API 文档，包括媒体库管理、媒体文件管理等功能
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ApiBackupHistoryGet200Response {
    /**
     * 业务状态码
     */
    'code'?: ResponseResponseCode;
    'data'?: ControllersBackupHistoryResponse;
    /**
     * 消息
     */
    'msg'?: string;
    /**
     * 时间戳
     */
    'timestamp'?: number;
}


export interface ApiBackupStatusGet200Response {
    /**
     * 业务状态码
     */
    'code'?: ResponseResponseCode;
    'data'?: ControllersBackupStatus;
    /**
     * 消息
     */
    'msg'?: string;
    /**
     * 时间戳
     */
    'timestamp'?: number;
}


export interface ApiResourceFile {
    'created_at'?: number;
    'file_name'?: string;
    'file_size'?: number;
    'id'?: number;
    'mime_type'?: string;
    'storage_type'?: string;
    'type'?: string;
    'url'?: string;
}
export interface ApiResourceListResponse {
    'page'?: number;
    'page_size'?: number;
    'resources'?: Array<ApiResourceFile>;
    'total'?: number;
}
export interface ApiResourcesGet200Response {
    /**
     * 业务状态码
     */
    'code'?: ResponseResponseCode;
    'data'?: ApiResourceListResponse;
    /**
     * 消息
     */
    'msg'?: string;
    /**
     * 时间戳
     */
    'timestamp'?: number;
}


export interface ApiResourcesUploadPost200Response {
    /**
     * 业务状态码
     */
    'code'?: ResponseResponseCode;
    'data'?: ApiUploadResourceResponse;
    /**
     * 消息
     */
    'msg'?: string;
    /**
     * 时间戳
     */
    'timestamp'?: number;
}


export interface ApiSecurityBlockIpPost200Response {
    /**
     * 业务状态码
     */
    'code'?: ResponseResponseCode;
    'data'?: ControllersBlockedIP;
    /**
     * 消息
     */
    'msg'?: string;
    /**
     * 时间戳
     */
    'timestamp'?: number;
}


export interface ApiSecurityBlockedIpsGet200Response {
    /**
     * 业务状态码
     */
    'code'?: ResponseResponseCode;
    'data'?: Array<ControllersBlockedIP>;
    /**
     * 消息
     */
    'msg'?: string;
    /**
     * 时间戳
     */
    'timestamp'?: number;
}


export interface ApiSecurityConnectionsGet200Response {
    /**
     * 业务状态码
     */
    'code'?: ResponseResponseCode;
    'data'?: ControllersConnectionStats;
    /**
     * 消息
     */
    'msg'?: string;
    /**
     * 时间戳
     */
    'timestamp'?: number;
}


export interface ApiSecurityIpStatsGet200Response {
    /**
     * 业务状态码
     */
    'code'?: ResponseResponseCode;
    'data'?: Array<ControllersIPStats>;
    /**
     * 消息
     */
    'msg'?: string;
    /**
     * 时间戳
     */
    'timestamp'?: number;
}


export interface ApiSecurityStatusGet200Response {
    /**
     * 业务状态码
     */
    'code'?: ResponseResponseCode;
    'data'?: ControllersSecurityStatus;
    /**
     * 消息
     */
    'msg'?: string;
    /**
     * 时间戳
     */
    'timestamp'?: number;
}


export interface ApiUploadResourceResponse {
    'file_name'?: string;
    'file_size'?: number;
    'mime_type'?: string;
    'resource_id'?: number;
    'type'?: string;
    'url'?: string;
}
export interface ControllersBackupHistoryResponse {
    'limit'?: number;
    'page'?: number;
    'records'?: Array<ControllersBackupRecord>;
    'total'?: number;
}
export interface ControllersBackupRecord {
    'description'?: string;
    'end_time'?: number;
    'error'?: string;
    'file_path'?: string;
    'file_size'?: number;
    'id'?: number;
    'start_time'?: number;
    'status'?: string;
    'type'?: string;
}
export interface ControllersBackupStatus {
    'failed_backups'?: number;
    'last_backup_time'?: number;
    'next_backup_time'?: number;
    'running'?: boolean;
    'successful_backups'?: number;
    'total_backups'?: number;
}
export interface ControllersBlockedIP {
    'blocked_at'?: number;
    'duration'?: number;
    'expires_at'?: number;
    'ip'?: string;
    'reason'?: string;
}
export interface ControllersConnectionStats {
    'active_connections'?: number;
    'ip_connections'?: { [key: string]: number; };
    'top_ips'?: Array<ControllersIPStats>;
    'total_connections'?: number;
}
export interface ControllersIPStats {
    'ip'?: string;
    'is_blocked'?: boolean;
    'is_whitelisted'?: boolean;
    'last_access'?: number;
    'request_count'?: number;
}
export interface ControllersSecurityStatus {
    'config'?: object;
    'rate_limiter_active'?: boolean;
    'threat_level'?: string;
    'uptime'?: number;
}
export interface ResponseResponse {
    /**
     * 业务状态码
     */
    'code'?: ResponseResponseCode;
    /**
     * 数据
     */
    'data'?: object;
    /**
     * 消息
     */
    'msg'?: string;
    /**
     * 时间戳
     */
    'timestamp'?: number;
}



export const ResponseResponseCode = {
    CodeSuccess: 200,
    CodeBadRequest: 400,
    CodeUnauthorized: 401,
    CodeForbidden: 403,
    CodeNotFound: 404,
    CodeMethodNotAllowed: 405,
    CodeConflict: 409,
    CodeUnprocessableEntity: 422,
    CodeTooManyRequests: 429,
    CodeInternalServerError: 500,
    CodeNotImplemented: 501,
    CodeBadGateway: 502,
    CodeServiceUnavailable: 503
} as const;

export type ResponseResponseCode = typeof ResponseResponseCode[keyof typeof ResponseResponseCode];



/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 单独执行CDN文件的增量备份操作
         * @summary 手动触发CDN增量备份
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBackupCdnPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/backup/cdn`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 单独执行数据库备份操作，不包括CDN文件
         * @summary 手动触发数据库备份
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBackupDatabasePost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/backup/database`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取系统所有备份操作的历史记录，包括成功和失败的备份
         * @summary 获取备份历史记录
         * @param {number} [page] 页码，默认1
         * @param {number} [limit] 每页数量，默认20，最大100
         * @param {string} [type] 备份类型筛选：database | cdn | full
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBackupHistoryGet: async (page?: number, limit?: number, type?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/backup/history`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 使用指定的备份记录恢复CDN文件到指定状态（谨慎操作）
         * @summary 从备份恢复CDN文件
         * @param {number} backupId 备份记录ID（示例: 1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBackupRestoreCdnBackupIdPost: async (backupId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'backupId' is not null or undefined
            assertParamExists('apiBackupRestoreCdnBackupIdPost', 'backupId', backupId)
            const localVarPath = `/api/backup/restore/cdn/{backup_id}`
                .replace(`{${"backup_id"}}`, encodeURIComponent(String(backupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取当前备份调度器和备份服务的运行状态信息
         * @summary 获取备份系统状态
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBackupStatusGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/backup/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 立即执行一次完整的系统备份，包括数据库和CDN文件
         * @summary 手动触发全量备份
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBackupTriggerPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/backup/trigger`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 检查API服务是否正常运行
         * @summary 健康检查
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPingGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ping`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取系统中所有资源文件的列表，支持分页和类型筛选
         * @summary 获取资源文件列表
         * @param {number} [page] 页码，默认1
         * @param {number} [pageSize] 每页数量，默认10，最大100
         * @param {string} [type] 资源类型筛选：image | video | audio | document
         * @param {number} [libraryId] 媒体库ID筛选
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiResourcesGet: async (page?: number, pageSize?: number, type?: string, libraryId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/resources`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (libraryId !== undefined) {
                localVarQueryParameter['library_id'] = libraryId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 永久删除指定的资源文件，包括本地和CDN存储
         * @summary 删除资源文件
         * @param {string} id 资源ID（示例: 1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiResourcesIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiResourcesIdDelete', 'id', id)
            const localVarPath = `/api/resources/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 根据ID获取资源文件，返回文件内容或重定向到CDN地址
         * @summary 获取资源文件
         * @param {string} id 资源ID（示例: 1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiResourcesIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiResourcesIdGet', 'id', id)
            const localVarPath = `/api/resources/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 上传各类资源文件（图片、文档、音频、视频等）到系统
         * @summary 上传资源文件
         * @param {File} file 资源文件（最大10MB）
         * @param {number} [libraryId] 媒体库ID，可选
         * @param {string} [resourceType] 资源类型（系统自动识别）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiResourcesUploadPost: async (file: File, libraryId?: number, resourceType?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'file' is not null or undefined
            assertParamExists('apiResourcesUploadPost', 'file', file)
            const localVarPath = `/api/resources/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            if (libraryId !== undefined) {
                localVarQueryParameter['library_id'] = libraryId;
            }


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
            if (resourceType !== undefined) { 
                localVarFormParams.append('resource_type', resourceType as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 将指定IP地址添加到黑名单，阻止其访问系统
         * @summary 手动封禁IP地址
         * @param {string} ip IP地址（示例: 192.168.1.100）
         * @param {number} [duration] 封禁时长(秒)，默认3600
         * @param {string} [reason] 封禁原因
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityBlockIpPost: async (ip: string, duration?: number, reason?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ip' is not null or undefined
            assertParamExists('apiSecurityBlockIpPost', 'ip', ip)
            const localVarPath = `/api/security/block/{ip}`
                .replace(`{${"ip"}}`, encodeURIComponent(String(ip)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (duration !== undefined) {
                localVarQueryParameter['duration'] = duration;
            }

            if (reason !== undefined) {
                localVarQueryParameter['reason'] = reason;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取当前被封禁的IP地址列表，包括封禁原因和到期时间
         * @summary 获取被封禁IP列表
         * @param {number} [page] 页码，默认1
         * @param {number} [limit] 每页数量，默认20
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityBlockedIpsGet: async (page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/security/blocked-ips`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取当前活跃连接统计信息，用于DDoS监控和流量分析
         * @summary 获取实时连接统计
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityConnectionsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/security/connections`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取各IP地址的访问次数、最后访问时间等统计信息
         * @summary 获取IP访问统计
         * @param {number} [page] 页码，默认1
         * @param {number} [limit] 每页数量，默认50
         * @param {string} [sort] 排序方式：request_count(请求数) | last_access(最后访问)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityIpStatsGet: async (page?: number, limit?: number, sort?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/security/ip-stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取当前安全中间件运行状态、配置信息和威胁等级
         * @summary 获取系统安全状态
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityStatusGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/security/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 将指定IP地址从黑名单中移除，恢复其正常访问权限
         * @summary 手动解封IP地址
         * @param {string} ip IP地址（示例: 192.168.1.100）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityUnblockIpPost: async (ip: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ip' is not null or undefined
            assertParamExists('apiSecurityUnblockIpPost', 'ip', ip)
            const localVarPath = `/api/security/unblock/{ip}`
                .replace(`{${"ip"}}`, encodeURIComponent(String(ip)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 将IP地址从白名单中移除，该IP将重新受到安全检查
         * @summary 从白名单移除IP
         * @param {string} ip IP地址（示例: 192.168.1.1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityWhitelistIpDelete: async (ip: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ip' is not null or undefined
            assertParamExists('apiSecurityWhitelistIpDelete', 'ip', ip)
            const localVarPath = `/api/security/whitelist/{ip}`
                .replace(`{${"ip"}}`, encodeURIComponent(String(ip)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 将IP地址添加到白名单，该IP将绕过所有安全检查
         * @summary 添加IP到白名单
         * @param {string} ip IP地址（示例: 192.168.1.1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityWhitelistIpPost: async (ip: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ip' is not null or undefined
            assertParamExists('apiSecurityWhitelistIpPost', 'ip', ip)
            const localVarPath = `/api/security/whitelist/{ip}`
                .replace(`{${"ip"}}`, encodeURIComponent(String(ip)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 单独执行CDN文件的增量备份操作
         * @summary 手动触发CDN增量备份
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBackupCdnPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBackupCdnPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiBackupCdnPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 单独执行数据库备份操作，不包括CDN文件
         * @summary 手动触发数据库备份
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBackupDatabasePost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBackupDatabasePost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiBackupDatabasePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 获取系统所有备份操作的历史记录，包括成功和失败的备份
         * @summary 获取备份历史记录
         * @param {number} [page] 页码，默认1
         * @param {number} [limit] 每页数量，默认20，最大100
         * @param {string} [type] 备份类型筛选：database | cdn | full
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBackupHistoryGet(page?: number, limit?: number, type?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiBackupHistoryGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBackupHistoryGet(page, limit, type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiBackupHistoryGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 使用指定的备份记录恢复CDN文件到指定状态（谨慎操作）
         * @summary 从备份恢复CDN文件
         * @param {number} backupId 备份记录ID（示例: 1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBackupRestoreCdnBackupIdPost(backupId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBackupRestoreCdnBackupIdPost(backupId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiBackupRestoreCdnBackupIdPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 获取当前备份调度器和备份服务的运行状态信息
         * @summary 获取备份系统状态
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBackupStatusGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiBackupStatusGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBackupStatusGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiBackupStatusGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 立即执行一次完整的系统备份，包括数据库和CDN文件
         * @summary 手动触发全量备份
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBackupTriggerPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBackupTriggerPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiBackupTriggerPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 检查API服务是否正常运行
         * @summary 健康检查
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPingGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiPingGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiPingGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 获取系统中所有资源文件的列表，支持分页和类型筛选
         * @summary 获取资源文件列表
         * @param {number} [page] 页码，默认1
         * @param {number} [pageSize] 每页数量，默认10，最大100
         * @param {string} [type] 资源类型筛选：image | video | audio | document
         * @param {number} [libraryId] 媒体库ID筛选
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiResourcesGet(page?: number, pageSize?: number, type?: string, libraryId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResourcesGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiResourcesGet(page, pageSize, type, libraryId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiResourcesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 永久删除指定的资源文件，包括本地和CDN存储
         * @summary 删除资源文件
         * @param {string} id 资源ID（示例: 1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiResourcesIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiResourcesIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiResourcesIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 根据ID获取资源文件，返回文件内容或重定向到CDN地址
         * @summary 获取资源文件
         * @param {string} id 资源ID（示例: 1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiResourcesIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiResourcesIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiResourcesIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 上传各类资源文件（图片、文档、音频、视频等）到系统
         * @summary 上传资源文件
         * @param {File} file 资源文件（最大10MB）
         * @param {number} [libraryId] 媒体库ID，可选
         * @param {string} [resourceType] 资源类型（系统自动识别）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiResourcesUploadPost(file: File, libraryId?: number, resourceType?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResourcesUploadPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiResourcesUploadPost(file, libraryId, resourceType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiResourcesUploadPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 将指定IP地址添加到黑名单，阻止其访问系统
         * @summary 手动封禁IP地址
         * @param {string} ip IP地址（示例: 192.168.1.100）
         * @param {number} [duration] 封禁时长(秒)，默认3600
         * @param {string} [reason] 封禁原因
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSecurityBlockIpPost(ip: string, duration?: number, reason?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiSecurityBlockIpPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSecurityBlockIpPost(ip, duration, reason, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiSecurityBlockIpPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 获取当前被封禁的IP地址列表，包括封禁原因和到期时间
         * @summary 获取被封禁IP列表
         * @param {number} [page] 页码，默认1
         * @param {number} [limit] 每页数量，默认20
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSecurityBlockedIpsGet(page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiSecurityBlockedIpsGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSecurityBlockedIpsGet(page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiSecurityBlockedIpsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 获取当前活跃连接统计信息，用于DDoS监控和流量分析
         * @summary 获取实时连接统计
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSecurityConnectionsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiSecurityConnectionsGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSecurityConnectionsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiSecurityConnectionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 获取各IP地址的访问次数、最后访问时间等统计信息
         * @summary 获取IP访问统计
         * @param {number} [page] 页码，默认1
         * @param {number} [limit] 每页数量，默认50
         * @param {string} [sort] 排序方式：request_count(请求数) | last_access(最后访问)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSecurityIpStatsGet(page?: number, limit?: number, sort?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiSecurityIpStatsGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSecurityIpStatsGet(page, limit, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiSecurityIpStatsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 获取当前安全中间件运行状态、配置信息和威胁等级
         * @summary 获取系统安全状态
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSecurityStatusGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiSecurityStatusGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSecurityStatusGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiSecurityStatusGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 将指定IP地址从黑名单中移除，恢复其正常访问权限
         * @summary 手动解封IP地址
         * @param {string} ip IP地址（示例: 192.168.1.100）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSecurityUnblockIpPost(ip: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSecurityUnblockIpPost(ip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiSecurityUnblockIpPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 将IP地址从白名单中移除，该IP将重新受到安全检查
         * @summary 从白名单移除IP
         * @param {string} ip IP地址（示例: 192.168.1.1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSecurityWhitelistIpDelete(ip: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSecurityWhitelistIpDelete(ip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiSecurityWhitelistIpDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 将IP地址添加到白名单，该IP将绕过所有安全检查
         * @summary 添加IP到白名单
         * @param {string} ip IP地址（示例: 192.168.1.1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSecurityWhitelistIpPost(ip: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSecurityWhitelistIpPost(ip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiSecurityWhitelistIpPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 单独执行CDN文件的增量备份操作
         * @summary 手动触发CDN增量备份
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBackupCdnPost(options?: RawAxiosRequestConfig): AxiosPromise<ResponseResponse> {
            return localVarFp.apiBackupCdnPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 单独执行数据库备份操作，不包括CDN文件
         * @summary 手动触发数据库备份
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBackupDatabasePost(options?: RawAxiosRequestConfig): AxiosPromise<ResponseResponse> {
            return localVarFp.apiBackupDatabasePost(options).then((request) => request(axios, basePath));
        },
        /**
         * 获取系统所有备份操作的历史记录，包括成功和失败的备份
         * @summary 获取备份历史记录
         * @param {number} [page] 页码，默认1
         * @param {number} [limit] 每页数量，默认20，最大100
         * @param {string} [type] 备份类型筛选：database | cdn | full
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBackupHistoryGet(page?: number, limit?: number, type?: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiBackupHistoryGet200Response> {
            return localVarFp.apiBackupHistoryGet(page, limit, type, options).then((request) => request(axios, basePath));
        },
        /**
         * 使用指定的备份记录恢复CDN文件到指定状态（谨慎操作）
         * @summary 从备份恢复CDN文件
         * @param {number} backupId 备份记录ID（示例: 1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBackupRestoreCdnBackupIdPost(backupId: number, options?: RawAxiosRequestConfig): AxiosPromise<ResponseResponse> {
            return localVarFp.apiBackupRestoreCdnBackupIdPost(backupId, options).then((request) => request(axios, basePath));
        },
        /**
         * 获取当前备份调度器和备份服务的运行状态信息
         * @summary 获取备份系统状态
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBackupStatusGet(options?: RawAxiosRequestConfig): AxiosPromise<ApiBackupStatusGet200Response> {
            return localVarFp.apiBackupStatusGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 立即执行一次完整的系统备份，包括数据库和CDN文件
         * @summary 手动触发全量备份
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBackupTriggerPost(options?: RawAxiosRequestConfig): AxiosPromise<ResponseResponse> {
            return localVarFp.apiBackupTriggerPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 检查API服务是否正常运行
         * @summary 健康检查
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPingGet(options?: RawAxiosRequestConfig): AxiosPromise<ResponseResponse> {
            return localVarFp.apiPingGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 获取系统中所有资源文件的列表，支持分页和类型筛选
         * @summary 获取资源文件列表
         * @param {number} [page] 页码，默认1
         * @param {number} [pageSize] 每页数量，默认10，最大100
         * @param {string} [type] 资源类型筛选：image | video | audio | document
         * @param {number} [libraryId] 媒体库ID筛选
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiResourcesGet(page?: number, pageSize?: number, type?: string, libraryId?: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiResourcesGet200Response> {
            return localVarFp.apiResourcesGet(page, pageSize, type, libraryId, options).then((request) => request(axios, basePath));
        },
        /**
         * 永久删除指定的资源文件，包括本地和CDN存储
         * @summary 删除资源文件
         * @param {string} id 资源ID（示例: 1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiResourcesIdDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ResponseResponse> {
            return localVarFp.apiResourcesIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 根据ID获取资源文件，返回文件内容或重定向到CDN地址
         * @summary 获取资源文件
         * @param {string} id 资源ID（示例: 1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiResourcesIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.apiResourcesIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 上传各类资源文件（图片、文档、音频、视频等）到系统
         * @summary 上传资源文件
         * @param {File} file 资源文件（最大10MB）
         * @param {number} [libraryId] 媒体库ID，可选
         * @param {string} [resourceType] 资源类型（系统自动识别）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiResourcesUploadPost(file: File, libraryId?: number, resourceType?: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResourcesUploadPost200Response> {
            return localVarFp.apiResourcesUploadPost(file, libraryId, resourceType, options).then((request) => request(axios, basePath));
        },
        /**
         * 将指定IP地址添加到黑名单，阻止其访问系统
         * @summary 手动封禁IP地址
         * @param {string} ip IP地址（示例: 192.168.1.100）
         * @param {number} [duration] 封禁时长(秒)，默认3600
         * @param {string} [reason] 封禁原因
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityBlockIpPost(ip: string, duration?: number, reason?: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiSecurityBlockIpPost200Response> {
            return localVarFp.apiSecurityBlockIpPost(ip, duration, reason, options).then((request) => request(axios, basePath));
        },
        /**
         * 获取当前被封禁的IP地址列表，包括封禁原因和到期时间
         * @summary 获取被封禁IP列表
         * @param {number} [page] 页码，默认1
         * @param {number} [limit] 每页数量，默认20
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityBlockedIpsGet(page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiSecurityBlockedIpsGet200Response> {
            return localVarFp.apiSecurityBlockedIpsGet(page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 获取当前活跃连接统计信息，用于DDoS监控和流量分析
         * @summary 获取实时连接统计
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityConnectionsGet(options?: RawAxiosRequestConfig): AxiosPromise<ApiSecurityConnectionsGet200Response> {
            return localVarFp.apiSecurityConnectionsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 获取各IP地址的访问次数、最后访问时间等统计信息
         * @summary 获取IP访问统计
         * @param {number} [page] 页码，默认1
         * @param {number} [limit] 每页数量，默认50
         * @param {string} [sort] 排序方式：request_count(请求数) | last_access(最后访问)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityIpStatsGet(page?: number, limit?: number, sort?: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiSecurityIpStatsGet200Response> {
            return localVarFp.apiSecurityIpStatsGet(page, limit, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 获取当前安全中间件运行状态、配置信息和威胁等级
         * @summary 获取系统安全状态
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityStatusGet(options?: RawAxiosRequestConfig): AxiosPromise<ApiSecurityStatusGet200Response> {
            return localVarFp.apiSecurityStatusGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 将指定IP地址从黑名单中移除，恢复其正常访问权限
         * @summary 手动解封IP地址
         * @param {string} ip IP地址（示例: 192.168.1.100）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityUnblockIpPost(ip: string, options?: RawAxiosRequestConfig): AxiosPromise<ResponseResponse> {
            return localVarFp.apiSecurityUnblockIpPost(ip, options).then((request) => request(axios, basePath));
        },
        /**
         * 将IP地址从白名单中移除，该IP将重新受到安全检查
         * @summary 从白名单移除IP
         * @param {string} ip IP地址（示例: 192.168.1.1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityWhitelistIpDelete(ip: string, options?: RawAxiosRequestConfig): AxiosPromise<ResponseResponse> {
            return localVarFp.apiSecurityWhitelistIpDelete(ip, options).then((request) => request(axios, basePath));
        },
        /**
         * 将IP地址添加到白名单，该IP将绕过所有安全检查
         * @summary 添加IP到白名单
         * @param {string} ip IP地址（示例: 192.168.1.1）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSecurityWhitelistIpPost(ip: string, options?: RawAxiosRequestConfig): AxiosPromise<ResponseResponse> {
            return localVarFp.apiSecurityWhitelistIpPost(ip, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 单独执行CDN文件的增量备份操作
     * @summary 手动触发CDN增量备份
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiBackupCdnPost(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiBackupCdnPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 单独执行数据库备份操作，不包括CDN文件
     * @summary 手动触发数据库备份
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiBackupDatabasePost(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiBackupDatabasePost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 获取系统所有备份操作的历史记录，包括成功和失败的备份
     * @summary 获取备份历史记录
     * @param {number} [page] 页码，默认1
     * @param {number} [limit] 每页数量，默认20，最大100
     * @param {string} [type] 备份类型筛选：database | cdn | full
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiBackupHistoryGet(page?: number, limit?: number, type?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiBackupHistoryGet(page, limit, type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 使用指定的备份记录恢复CDN文件到指定状态（谨慎操作）
     * @summary 从备份恢复CDN文件
     * @param {number} backupId 备份记录ID（示例: 1）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiBackupRestoreCdnBackupIdPost(backupId: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiBackupRestoreCdnBackupIdPost(backupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 获取当前备份调度器和备份服务的运行状态信息
     * @summary 获取备份系统状态
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiBackupStatusGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiBackupStatusGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 立即执行一次完整的系统备份，包括数据库和CDN文件
     * @summary 手动触发全量备份
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiBackupTriggerPost(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiBackupTriggerPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 检查API服务是否正常运行
     * @summary 健康检查
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiPingGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiPingGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 获取系统中所有资源文件的列表，支持分页和类型筛选
     * @summary 获取资源文件列表
     * @param {number} [page] 页码，默认1
     * @param {number} [pageSize] 每页数量，默认10，最大100
     * @param {string} [type] 资源类型筛选：image | video | audio | document
     * @param {number} [libraryId] 媒体库ID筛选
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiResourcesGet(page?: number, pageSize?: number, type?: string, libraryId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiResourcesGet(page, pageSize, type, libraryId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 永久删除指定的资源文件，包括本地和CDN存储
     * @summary 删除资源文件
     * @param {string} id 资源ID（示例: 1）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiResourcesIdDelete(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiResourcesIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 根据ID获取资源文件，返回文件内容或重定向到CDN地址
     * @summary 获取资源文件
     * @param {string} id 资源ID（示例: 1）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiResourcesIdGet(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiResourcesIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 上传各类资源文件（图片、文档、音频、视频等）到系统
     * @summary 上传资源文件
     * @param {File} file 资源文件（最大10MB）
     * @param {number} [libraryId] 媒体库ID，可选
     * @param {string} [resourceType] 资源类型（系统自动识别）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiResourcesUploadPost(file: File, libraryId?: number, resourceType?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiResourcesUploadPost(file, libraryId, resourceType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 将指定IP地址添加到黑名单，阻止其访问系统
     * @summary 手动封禁IP地址
     * @param {string} ip IP地址（示例: 192.168.1.100）
     * @param {number} [duration] 封禁时长(秒)，默认3600
     * @param {string} [reason] 封禁原因
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSecurityBlockIpPost(ip: string, duration?: number, reason?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiSecurityBlockIpPost(ip, duration, reason, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 获取当前被封禁的IP地址列表，包括封禁原因和到期时间
     * @summary 获取被封禁IP列表
     * @param {number} [page] 页码，默认1
     * @param {number} [limit] 每页数量，默认20
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSecurityBlockedIpsGet(page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiSecurityBlockedIpsGet(page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 获取当前活跃连接统计信息，用于DDoS监控和流量分析
     * @summary 获取实时连接统计
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSecurityConnectionsGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiSecurityConnectionsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 获取各IP地址的访问次数、最后访问时间等统计信息
     * @summary 获取IP访问统计
     * @param {number} [page] 页码，默认1
     * @param {number} [limit] 每页数量，默认50
     * @param {string} [sort] 排序方式：request_count(请求数) | last_access(最后访问)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSecurityIpStatsGet(page?: number, limit?: number, sort?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiSecurityIpStatsGet(page, limit, sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 获取当前安全中间件运行状态、配置信息和威胁等级
     * @summary 获取系统安全状态
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSecurityStatusGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiSecurityStatusGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 将指定IP地址从黑名单中移除，恢复其正常访问权限
     * @summary 手动解封IP地址
     * @param {string} ip IP地址（示例: 192.168.1.100）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSecurityUnblockIpPost(ip: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiSecurityUnblockIpPost(ip, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 将IP地址从白名单中移除，该IP将重新受到安全检查
     * @summary 从白名单移除IP
     * @param {string} ip IP地址（示例: 192.168.1.1）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSecurityWhitelistIpDelete(ip: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiSecurityWhitelistIpDelete(ip, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 将IP地址添加到白名单，该IP将绕过所有安全检查
     * @summary 添加IP到白名单
     * @param {string} ip IP地址（示例: 192.168.1.1）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSecurityWhitelistIpPost(ip: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiSecurityWhitelistIpPost(ip, options).then((request) => request(this.axios, this.basePath));
    }
}



